# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    master:
     - step:
        caches:
          - node
        script:
          - npm install
          - npm test
     - step:
        caches:
         - node
        script:
         - apt-get update
         - apt-get install -y zip
         - zip -r app.zip .
         - pipe: atlassian/aws-code-deploy:0.2.5
           variables:
             AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             APPLICATION_NAME: $APPLICATION_NAME
             S3_BUCKET: $S3_BUCKET
             COMMAND: 'upload'
             ZIP_FILE: 'app.zip'
             VERSION_LABEL: 'kodede-1.0.0'
         - pipe: atlassian/aws-code-deploy:0.2.5
           variables:
             AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             APPLICATION_NAME: $APPLICATION_NAME
             DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
             S3_BUCKET: $S3_BUCKET
             COMMAND: 'deploy'
             WAIT: 'true'
             VERSION_LABEL: 'kodede-1.0.0'
             IGNORE_APPLICATION_STOP_FAILURES: 'true'
             FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
