version: '3'
services:
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    env_file:
      - .env

  dispatcher:
    restart: unless-stopped
    image: lscr.io/linuxserver/swag
    container_name: dispatcher
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - URL=tasttlig.com
      - VALIDATION=http
      - SUBDOMAINS=apitest,api-test
      - ONLY_SUBDOMAINS=true
      - EMAIL= hdamoo@tasttlig.com
      - STAGING=false
    volumes:
      - /var/app:/config
      - /var/log/nginx:/config/log/nginx
      - ./.config/nginx/site-confs/default:/config/nginx/site-confs/default
      - ./.config/etc/letsencrypt/options-ssl-nginx.conf:/config/etc/letsencrypt/options-ssl-nginx.conf
      - ./.config/etc/letsencrypt/ssl-dhparams.pem:/config/etc/letsencrypt/ssl-dhparams.pem
      - ./.config/fail2ban/jail.local:/config/fail2ban/jail.local
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - api